/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface User {
    id: number;
    name: string;
    username: string;
    /** @nullable */
    bio?: string | null;
    /** @nullable */
    defaultPhotoId?: number | null;
    createdAt: string;
}
export interface UserUpdate {
    /** @minLength 1 */
    name?: string;
    bio?: string;
}
export interface UserStats {
    totalPhotos: number;
    activeRules: number;
    totalContacts: number;
    totalLists: number;
    /** @nullable */
    publicPhotoId: number | null;
}
export interface ProfilePhoto {
    id: number;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    /** @nullable */
    visibilityType?: string | null;
    createdAt: string;
}
export interface PhotoInput {
    /** @minLength 1 */
    label: string;
    imageUrl: string;
    isDefault?: boolean;
}
export interface PhotoUpdate {
    /** @minLength 1 */
    label?: string;
    isDefault?: boolean;
}
export type VisibilityType = typeof VisibilityType[keyof typeof VisibilityType];
export declare const VisibilityType: {
    readonly public: "public";
    readonly contacts: "contacts";
    readonly selected: "selected";
    readonly custom_list: "custom_list";
    readonly nobody: "nobody";
};
export interface VisibilityRule {
    photoId: number;
    type: VisibilityType;
    selectedContactIds?: number[];
    /** @nullable */
    listId?: number | null;
    excludedContactIds?: number[];
}
export interface VisibilityInput {
    type: VisibilityType;
    selectedContactIds?: number[];
    /** @nullable */
    listId?: number | null;
    excludedContactIds?: number[];
}
export interface VisibilityPreview {
    contactId: number;
    photoId: number;
    reason: string;
    photo?: ProfilePhoto;
}
export interface Contact {
    id: number;
    userId: number;
    name: string;
    /** @nullable */
    handle?: string | null;
    /** @nullable */
    avatarUrl?: string | null;
    listIds?: number[];
    createdAt: string;
}
export interface ContactInput {
    /** @minLength 1 */
    name: string;
    handle?: string;
    avatarUrl?: string;
}
export interface ContactUpdate {
    /** @minLength 1 */
    name?: string;
    handle?: string;
    avatarUrl?: string;
}
export interface ContactList {
    id: number;
    userId: number;
    name: string;
    memberCount: number;
    createdAt: string;
}
export interface ContactListInput {
    /** @minLength 1 */
    name: string;
}
export interface ContactListUpdate {
    /** @minLength 1 */
    name?: string;
}
export interface ListMemberInput {
    contactId: number;
}
export interface StorageUploadRequest {
    /**
       * Original file name
       * @minLength 1
       */
    name: string;
    /**
       * File size in bytes
       * @minimum 1
       */
    size: number;
    /**
       * MIME type (e.g. image/jpeg)
       * @minLength 1
       */
    contentType: string;
}
export interface StorageUploadResponse {
    /** Presigned GCS URL for PUT upload */
    uploadURL: string;
    /** Normalized object path (e.g. /objects/uploads/uuid) */
    objectPath: string;
}
export interface ErrorEnvelope {
    error: string;
}
//# sourceMappingURL=api.schemas.d.ts.map