/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';
/**
 * Returns a presigned GCS URL for direct upload. Send JSON metadata only — NOT the file.
Then upload the file directly to the returned presigned URL via PUT.

 * @summary Request a presigned URL for file upload
 */
export declare const RequestUploadUrlBody: zod.ZodObject<{
    name: zod.ZodString;
    size: zod.ZodNumber;
    contentType: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
    size: number;
    contentType: string;
}, {
    name: string;
    size: number;
    contentType: string;
}>;
export declare const RequestUploadUrlResponse: zod.ZodObject<{
    uploadURL: zod.ZodString;
    objectPath: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    uploadURL: string;
    objectPath: string;
}, {
    uploadURL: string;
    objectPath: string;
}>;
/**
 * @summary Serve an uploaded object
 */
export declare const GetStorageObjectParams: zod.ZodObject<{
    objectPath: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    objectPath: string;
}, {
    objectPath: string;
}>;
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Get current user profile
 */
export declare const GetMeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    username: zod.ZodString;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    defaultPhotoId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    username: string;
    createdAt: Date;
    bio?: string | null | undefined;
    defaultPhotoId?: number | null | undefined;
}, {
    name: string;
    id: number;
    username: string;
    createdAt: Date;
    bio?: string | null | undefined;
    defaultPhotoId?: number | null | undefined;
}>;
/**
 * @summary Update current user profile
 */
export declare const UpdateMeBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    bio: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
    bio?: string | undefined;
}, {
    name?: string | undefined;
    bio?: string | undefined;
}>;
export declare const UpdateMeResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    username: zod.ZodString;
    bio: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    defaultPhotoId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    username: string;
    createdAt: Date;
    bio?: string | null | undefined;
    defaultPhotoId?: number | null | undefined;
}, {
    name: string;
    id: number;
    username: string;
    createdAt: Date;
    bio?: string | null | undefined;
    defaultPhotoId?: number | null | undefined;
}>;
/**
 * @summary Get dashboard summary stats
 */
export declare const GetMyStatsResponse: zod.ZodObject<{
    totalPhotos: zod.ZodNumber;
    activeRules: zod.ZodNumber;
    totalContacts: zod.ZodNumber;
    totalLists: zod.ZodNumber;
    publicPhotoId: zod.ZodNullable<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    totalPhotos: number;
    activeRules: number;
    totalContacts: number;
    totalLists: number;
    publicPhotoId: number | null;
}, {
    totalPhotos: number;
    activeRules: number;
    totalContacts: number;
    totalLists: number;
    publicPhotoId: number | null;
}>;
/**
 * @summary List all profile photos for current user
 */
export declare const ListPhotosResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    label: zod.ZodString;
    imageUrl: zod.ZodString;
    isDefault: zod.ZodBoolean;
    visibilityType: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    visibilityType?: string | null | undefined;
}, {
    id: number;
    createdAt: Date;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    visibilityType?: string | null | undefined;
}>;
export declare const ListPhotosResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    label: zod.ZodString;
    imageUrl: zod.ZodString;
    isDefault: zod.ZodBoolean;
    visibilityType: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    visibilityType?: string | null | undefined;
}, {
    id: number;
    createdAt: Date;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    visibilityType?: string | null | undefined;
}>, "many">;
/**
 * @summary Upload a new profile photo
 */
export declare const CreatePhotoBody: zod.ZodObject<{
    label: zod.ZodString;
    imageUrl: zod.ZodString;
    isDefault: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    label: string;
    imageUrl: string;
    isDefault?: boolean | undefined;
}, {
    label: string;
    imageUrl: string;
    isDefault?: boolean | undefined;
}>;
/**
 * @summary Get a specific profile photo
 */
export declare const GetPhotoParams: zod.ZodObject<{
    photoId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    photoId: number;
}, {
    photoId: number;
}>;
export declare const GetPhotoResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    label: zod.ZodString;
    imageUrl: zod.ZodString;
    isDefault: zod.ZodBoolean;
    visibilityType: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    visibilityType?: string | null | undefined;
}, {
    id: number;
    createdAt: Date;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    visibilityType?: string | null | undefined;
}>;
/**
 * @summary Update photo label or set as default
 */
export declare const UpdatePhotoParams: zod.ZodObject<{
    photoId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    photoId: number;
}, {
    photoId: number;
}>;
export declare const UpdatePhotoBody: zod.ZodObject<{
    label: zod.ZodOptional<zod.ZodString>;
    isDefault: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    label?: string | undefined;
    isDefault?: boolean | undefined;
}, {
    label?: string | undefined;
    isDefault?: boolean | undefined;
}>;
export declare const UpdatePhotoResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    label: zod.ZodString;
    imageUrl: zod.ZodString;
    isDefault: zod.ZodBoolean;
    visibilityType: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    visibilityType?: string | null | undefined;
}, {
    id: number;
    createdAt: Date;
    userId: number;
    label: string;
    imageUrl: string;
    isDefault: boolean;
    visibilityType?: string | null | undefined;
}>;
/**
 * @summary Delete a profile photo
 */
export declare const DeletePhotoParams: zod.ZodObject<{
    photoId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    photoId: number;
}, {
    photoId: number;
}>;
/**
 * @summary Get visibility rule for a photo
 */
export declare const GetPhotoVisibilityParams: zod.ZodObject<{
    photoId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    photoId: number;
}, {
    photoId: number;
}>;
export declare const GetPhotoVisibilityResponse: zod.ZodObject<{
    photoId: zod.ZodNumber;
    type: zod.ZodEnum<["public", "contacts", "selected", "custom_list", "nobody"]>;
    selectedContactIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
    listId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    excludedContactIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
}, "strip", zod.ZodTypeAny, {
    type: "public" | "contacts" | "selected" | "custom_list" | "nobody";
    photoId: number;
    selectedContactIds?: number[] | undefined;
    listId?: number | null | undefined;
    excludedContactIds?: number[] | undefined;
}, {
    type: "public" | "contacts" | "selected" | "custom_list" | "nobody";
    photoId: number;
    selectedContactIds?: number[] | undefined;
    listId?: number | null | undefined;
    excludedContactIds?: number[] | undefined;
}>;
/**
 * @summary Set visibility rule for a photo
 */
export declare const SetPhotoVisibilityParams: zod.ZodObject<{
    photoId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    photoId: number;
}, {
    photoId: number;
}>;
export declare const SetPhotoVisibilityBody: zod.ZodObject<{
    type: zod.ZodEnum<["public", "contacts", "selected", "custom_list", "nobody"]>;
    selectedContactIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
    listId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    excludedContactIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
}, "strip", zod.ZodTypeAny, {
    type: "public" | "contacts" | "selected" | "custom_list" | "nobody";
    selectedContactIds?: number[] | undefined;
    listId?: number | null | undefined;
    excludedContactIds?: number[] | undefined;
}, {
    type: "public" | "contacts" | "selected" | "custom_list" | "nobody";
    selectedContactIds?: number[] | undefined;
    listId?: number | null | undefined;
    excludedContactIds?: number[] | undefined;
}>;
export declare const SetPhotoVisibilityResponse: zod.ZodObject<{
    photoId: zod.ZodNumber;
    type: zod.ZodEnum<["public", "contacts", "selected", "custom_list", "nobody"]>;
    selectedContactIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
    listId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    excludedContactIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
}, "strip", zod.ZodTypeAny, {
    type: "public" | "contacts" | "selected" | "custom_list" | "nobody";
    photoId: number;
    selectedContactIds?: number[] | undefined;
    listId?: number | null | undefined;
    excludedContactIds?: number[] | undefined;
}, {
    type: "public" | "contacts" | "selected" | "custom_list" | "nobody";
    photoId: number;
    selectedContactIds?: number[] | undefined;
    listId?: number | null | undefined;
    excludedContactIds?: number[] | undefined;
}>;
/**
 * @summary Preview which photo a specific contact would see
 */
export declare const PreviewAsContactParams: zod.ZodObject<{
    contactId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    contactId: number;
}, {
    contactId: number;
}>;
export declare const PreviewAsContactResponse: zod.ZodObject<{
    contactId: zod.ZodNumber;
    photoId: zod.ZodNumber;
    reason: zod.ZodString;
    photo: zod.ZodOptional<zod.ZodObject<{
        id: zod.ZodNumber;
        userId: zod.ZodNumber;
        label: zod.ZodString;
        imageUrl: zod.ZodString;
        isDefault: zod.ZodBoolean;
        visibilityType: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        userId: number;
        label: string;
        imageUrl: string;
        isDefault: boolean;
        visibilityType?: string | null | undefined;
    }, {
        id: number;
        createdAt: Date;
        userId: number;
        label: string;
        imageUrl: string;
        isDefault: boolean;
        visibilityType?: string | null | undefined;
    }>>;
}, "strip", zod.ZodTypeAny, {
    photoId: number;
    contactId: number;
    reason: string;
    photo?: {
        id: number;
        createdAt: Date;
        userId: number;
        label: string;
        imageUrl: string;
        isDefault: boolean;
        visibilityType?: string | null | undefined;
    } | undefined;
}, {
    photoId: number;
    contactId: number;
    reason: string;
    photo?: {
        id: number;
        createdAt: Date;
        userId: number;
        label: string;
        imageUrl: string;
        isDefault: boolean;
        visibilityType?: string | null | undefined;
    } | undefined;
}>;
/**
 * @summary List all contacts
 */
export declare const ListContactsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    name: zod.ZodString;
    handle: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    listIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}>;
export declare const ListContactsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    name: zod.ZodString;
    handle: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    listIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}>, "many">;
/**
 * @summary Add a new contact
 */
export declare const CreateContactBody: zod.ZodObject<{
    name: zod.ZodString;
    handle: zod.ZodOptional<zod.ZodString>;
    avatarUrl: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    handle?: string | undefined;
    avatarUrl?: string | undefined;
}, {
    name: string;
    handle?: string | undefined;
    avatarUrl?: string | undefined;
}>;
/**
 * @summary Update a contact
 */
export declare const UpdateContactParams: zod.ZodObject<{
    contactId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    contactId: number;
}, {
    contactId: number;
}>;
export declare const UpdateContactBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    handle: zod.ZodOptional<zod.ZodString>;
    avatarUrl: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
    handle?: string | undefined;
    avatarUrl?: string | undefined;
}, {
    name?: string | undefined;
    handle?: string | undefined;
    avatarUrl?: string | undefined;
}>;
export declare const UpdateContactResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    name: zod.ZodString;
    handle: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    listIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}>;
/**
 * @summary Remove a contact
 */
export declare const DeleteContactParams: zod.ZodObject<{
    contactId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    contactId: number;
}, {
    contactId: number;
}>;
/**
 * @summary List all custom contact lists
 */
export declare const ListContactListsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    name: zod.ZodString;
    memberCount: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    memberCount: number;
}, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    memberCount: number;
}>;
export declare const ListContactListsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    name: zod.ZodString;
    memberCount: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    memberCount: number;
}, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    memberCount: number;
}>, "many">;
/**
 * @summary Create a custom contact list
 */
export declare const CreateContactListBody: zod.ZodObject<{
    name: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
}, {
    name: string;
}>;
/**
 * @summary Rename a contact list
 */
export declare const UpdateContactListParams: zod.ZodObject<{
    listId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    listId: number;
}, {
    listId: number;
}>;
export declare const UpdateContactListBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
}, {
    name?: string | undefined;
}>;
export declare const UpdateContactListResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    name: zod.ZodString;
    memberCount: zod.ZodNumber;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    memberCount: number;
}, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    memberCount: number;
}>;
/**
 * @summary Delete a custom list
 */
export declare const DeleteContactListParams: zod.ZodObject<{
    listId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    listId: number;
}, {
    listId: number;
}>;
/**
 * @summary Get members of a list
 */
export declare const ListContactListMembersParams: zod.ZodObject<{
    listId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    listId: number;
}, {
    listId: number;
}>;
export declare const ListContactListMembersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    name: zod.ZodString;
    handle: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    listIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}>;
export declare const ListContactListMembersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodNumber;
    name: zod.ZodString;
    handle: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    avatarUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    listIds: zod.ZodOptional<zod.ZodArray<zod.ZodNumber, "many">>;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}, {
    name: string;
    id: number;
    createdAt: Date;
    userId: number;
    handle?: string | null | undefined;
    avatarUrl?: string | null | undefined;
    listIds?: number[] | undefined;
}>, "many">;
/**
 * @summary Add a contact to a list
 */
export declare const AddContactToListParams: zod.ZodObject<{
    listId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    listId: number;
}, {
    listId: number;
}>;
export declare const AddContactToListBody: zod.ZodObject<{
    contactId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    contactId: number;
}, {
    contactId: number;
}>;
/**
 * @summary Remove a contact from a list
 */
export declare const RemoveContactFromListParams: zod.ZodObject<{
    listId: zod.ZodNumber;
    contactId: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    listId: number;
    contactId: number;
}, {
    listId: number;
    contactId: number;
}>;
//# sourceMappingURL=api.d.ts.map