/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Contact,
  ContactInput,
  ContactList,
  ContactListInput,
  ContactListUpdate,
  ContactUpdate,
  ErrorEnvelope,
  HealthStatus,
  ListMemberInput,
  PhotoInput,
  PhotoUpdate,
  ProfilePhoto,
  StorageUploadRequest,
  StorageUploadResponse,
  User,
  UserStats,
  UserUpdate,
  VisibilityInput,
  VisibilityPreview,
  VisibilityRule
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType , BodyType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getRequestUploadUrlUrl = () => {




  return `/api/storage/uploads/request-url`
}

/**
 * Returns a presigned GCS URL for direct upload. Send JSON metadata only — NOT the file.
Then upload the file directly to the returned presigned URL via PUT.

 * @summary Request a presigned URL for file upload
 */
export const requestUploadUrl = async (storageUploadRequest: StorageUploadRequest, options?: RequestInit): Promise<StorageUploadResponse> => {

  return customFetch<StorageUploadResponse>(getRequestUploadUrlUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      storageUploadRequest,)
  }
);}




export const getRequestUploadUrlMutationOptions = <TError = ErrorType<ErrorEnvelope>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestUploadUrl>>, TError,{data: BodyType<StorageUploadRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof requestUploadUrl>>, TError,{data: BodyType<StorageUploadRequest>}, TContext> => {

const mutationKey = ['requestUploadUrl'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof requestUploadUrl>>, {data: BodyType<StorageUploadRequest>}> = (props) => {
          const {data} = props ?? {};

          return  requestUploadUrl(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RequestUploadUrlMutationResult = NonNullable<Awaited<ReturnType<typeof requestUploadUrl>>>
    export type RequestUploadUrlMutationBody = BodyType<StorageUploadRequest>
    export type RequestUploadUrlMutationError = ErrorType<ErrorEnvelope>

    /**
 * @summary Request a presigned URL for file upload
 */
export const useRequestUploadUrl = <TError = ErrorType<ErrorEnvelope>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof requestUploadUrl>>, TError,{data: BodyType<StorageUploadRequest>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof requestUploadUrl>>,
        TError,
        {data: BodyType<StorageUploadRequest>},
        TContext
      > => {
      return useMutation(getRequestUploadUrlMutationOptions(options));
    }

export const getGetStorageObjectUrl = (objectPath: string,) => {




  return `/api/storage/objects/${objectPath}`
}

/**
 * @summary Serve an uploaded object
 */
export const getStorageObject = async (objectPath: string, options?: RequestInit): Promise<Blob> => {

  return customFetch<Blob>(getGetStorageObjectUrl(objectPath),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStorageObjectQueryKey = (objectPath: string,) => {
    return [
    `/api/storage/objects/${objectPath}`
    ] as const;
    }


export const getGetStorageObjectQueryOptions = <TData = Awaited<ReturnType<typeof getStorageObject>>, TError = ErrorType<ErrorEnvelope>>(objectPath: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStorageObject>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStorageObjectQueryKey(objectPath);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStorageObject>>> = ({ signal }) => getStorageObject(objectPath, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(objectPath), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStorageObject>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStorageObjectQueryResult = NonNullable<Awaited<ReturnType<typeof getStorageObject>>>
export type GetStorageObjectQueryError = ErrorType<ErrorEnvelope>


/**
 * @summary Serve an uploaded object
 */

export function useGetStorageObject<TData = Awaited<ReturnType<typeof getStorageObject>>, TError = ErrorType<ErrorEnvelope>>(
 objectPath: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getStorageObject>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStorageObjectQueryOptions(objectPath,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetMeUrl = () => {




  return `/api/me`
}

/**
 * @summary Get current user profile
 */
export const getMe = async ( options?: RequestInit): Promise<User> => {

  return customFetch<User>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<unknown>


/**
 * @summary Get current user profile
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateMeUrl = () => {




  return `/api/me`
}

/**
 * @summary Update current user profile
 */
export const updateMe = async (userUpdate: UserUpdate, options?: RequestInit): Promise<User> => {

  return customFetch<User>(getUpdateMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userUpdate,)
  }
);}




export const getUpdateMeMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext> => {

const mutationKey = ['updateMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMe>>, {data: BodyType<UserUpdate>}> = (props) => {
          const {data} = props ?? {};

          return  updateMe(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMeMutationResult = NonNullable<Awaited<ReturnType<typeof updateMe>>>
    export type UpdateMeMutationBody = BodyType<UserUpdate>
    export type UpdateMeMutationError = ErrorType<unknown>

    /**
 * @summary Update current user profile
 */
export const useUpdateMe = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMe>>, TError,{data: BodyType<UserUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateMe>>,
        TError,
        {data: BodyType<UserUpdate>},
        TContext
      > => {
      return useMutation(getUpdateMeMutationOptions(options));
    }

export const getGetMyStatsUrl = () => {




  return `/api/me/stats`
}

/**
 * @summary Get dashboard summary stats
 */
export const getMyStats = async ( options?: RequestInit): Promise<UserStats> => {

  return customFetch<UserStats>(getGetMyStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMyStatsQueryKey = () => {
    return [
    `/api/me/stats`
    ] as const;
    }


export const getGetMyStatsQueryOptions = <TData = Awaited<ReturnType<typeof getMyStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyStats>>> = ({ signal }) => getMyStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMyStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getMyStats>>>
export type GetMyStatsQueryError = ErrorType<unknown>


/**
 * @summary Get dashboard summary stats
 */

export function useGetMyStats<TData = Awaited<ReturnType<typeof getMyStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMyStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMyStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListPhotosUrl = () => {




  return `/api/photos`
}

/**
 * @summary List all profile photos for current user
 */
export const listPhotos = async ( options?: RequestInit): Promise<ProfilePhoto[]> => {

  return customFetch<ProfilePhoto[]>(getListPhotosUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPhotosQueryKey = () => {
    return [
    `/api/photos`
    ] as const;
    }


export const getListPhotosQueryOptions = <TData = Awaited<ReturnType<typeof listPhotos>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPhotosQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPhotos>>> = ({ signal }) => listPhotos({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData> & { queryKey: QueryKey }
}

export type ListPhotosQueryResult = NonNullable<Awaited<ReturnType<typeof listPhotos>>>
export type ListPhotosQueryError = ErrorType<unknown>


/**
 * @summary List all profile photos for current user
 */

export function useListPhotos<TData = Awaited<ReturnType<typeof listPhotos>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listPhotos>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListPhotosQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreatePhotoUrl = () => {




  return `/api/photos`
}

/**
 * @summary Upload a new profile photo
 */
export const createPhoto = async (photoInput: PhotoInput, options?: RequestInit): Promise<ProfilePhoto> => {

  return customFetch<ProfilePhoto>(getCreatePhotoUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      photoInput,)
  }
);}




export const getCreatePhotoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPhoto>>, TError,{data: BodyType<PhotoInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createPhoto>>, TError,{data: BodyType<PhotoInput>}, TContext> => {

const mutationKey = ['createPhoto'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPhoto>>, {data: BodyType<PhotoInput>}> = (props) => {
          const {data} = props ?? {};

          return  createPhoto(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePhotoMutationResult = NonNullable<Awaited<ReturnType<typeof createPhoto>>>
    export type CreatePhotoMutationBody = BodyType<PhotoInput>
    export type CreatePhotoMutationError = ErrorType<unknown>

    /**
 * @summary Upload a new profile photo
 */
export const useCreatePhoto = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPhoto>>, TError,{data: BodyType<PhotoInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createPhoto>>,
        TError,
        {data: BodyType<PhotoInput>},
        TContext
      > => {
      return useMutation(getCreatePhotoMutationOptions(options));
    }

export const getGetPhotoUrl = (photoId: number,) => {




  return `/api/photos/${photoId}`
}

/**
 * @summary Get a specific profile photo
 */
export const getPhoto = async (photoId: number, options?: RequestInit): Promise<ProfilePhoto> => {

  return customFetch<ProfilePhoto>(getGetPhotoUrl(photoId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPhotoQueryKey = (photoId: number,) => {
    return [
    `/api/photos/${photoId}`
    ] as const;
    }


export const getGetPhotoQueryOptions = <TData = Awaited<ReturnType<typeof getPhoto>>, TError = ErrorType<unknown>>(photoId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPhotoQueryKey(photoId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhoto>>> = ({ signal }) => getPhoto(photoId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(photoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPhotoQueryResult = NonNullable<Awaited<ReturnType<typeof getPhoto>>>
export type GetPhotoQueryError = ErrorType<unknown>


/**
 * @summary Get a specific profile photo
 */

export function useGetPhoto<TData = Awaited<ReturnType<typeof getPhoto>>, TError = ErrorType<unknown>>(
 photoId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPhoto>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPhotoQueryOptions(photoId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdatePhotoUrl = (photoId: number,) => {




  return `/api/photos/${photoId}`
}

/**
 * @summary Update photo label or set as default
 */
export const updatePhoto = async (photoId: number,
    photoUpdate: PhotoUpdate, options?: RequestInit): Promise<ProfilePhoto> => {

  return customFetch<ProfilePhoto>(getUpdatePhotoUrl(photoId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      photoUpdate,)
  }
);}




export const getUpdatePhotoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePhoto>>, TError,{photoId: number;data: BodyType<PhotoUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updatePhoto>>, TError,{photoId: number;data: BodyType<PhotoUpdate>}, TContext> => {

const mutationKey = ['updatePhoto'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePhoto>>, {photoId: number;data: BodyType<PhotoUpdate>}> = (props) => {
          const {photoId,data} = props ?? {};

          return  updatePhoto(photoId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePhotoMutationResult = NonNullable<Awaited<ReturnType<typeof updatePhoto>>>
    export type UpdatePhotoMutationBody = BodyType<PhotoUpdate>
    export type UpdatePhotoMutationError = ErrorType<unknown>

    /**
 * @summary Update photo label or set as default
 */
export const useUpdatePhoto = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePhoto>>, TError,{photoId: number;data: BodyType<PhotoUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updatePhoto>>,
        TError,
        {photoId: number;data: BodyType<PhotoUpdate>},
        TContext
      > => {
      return useMutation(getUpdatePhotoMutationOptions(options));
    }

export const getDeletePhotoUrl = (photoId: number,) => {




  return `/api/photos/${photoId}`
}

/**
 * @summary Delete a profile photo
 */
export const deletePhoto = async (photoId: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeletePhotoUrl(photoId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeletePhotoMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePhoto>>, TError,{photoId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePhoto>>, TError,{photoId: number}, TContext> => {

const mutationKey = ['deletePhoto'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePhoto>>, {photoId: number}> = (props) => {
          const {photoId} = props ?? {};

          return  deletePhoto(photoId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePhotoMutationResult = NonNullable<Awaited<ReturnType<typeof deletePhoto>>>

    export type DeletePhotoMutationError = ErrorType<unknown>

    /**
 * @summary Delete a profile photo
 */
export const useDeletePhoto = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePhoto>>, TError,{photoId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deletePhoto>>,
        TError,
        {photoId: number},
        TContext
      > => {
      return useMutation(getDeletePhotoMutationOptions(options));
    }

export const getGetPhotoVisibilityUrl = (photoId: number,) => {




  return `/api/photos/${photoId}/visibility`
}

/**
 * @summary Get visibility rule for a photo
 */
export const getPhotoVisibility = async (photoId: number, options?: RequestInit): Promise<VisibilityRule> => {

  return customFetch<VisibilityRule>(getGetPhotoVisibilityUrl(photoId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPhotoVisibilityQueryKey = (photoId: number,) => {
    return [
    `/api/photos/${photoId}/visibility`
    ] as const;
    }


export const getGetPhotoVisibilityQueryOptions = <TData = Awaited<ReturnType<typeof getPhotoVisibility>>, TError = ErrorType<unknown>>(photoId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPhotoVisibility>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPhotoVisibilityQueryKey(photoId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhotoVisibility>>> = ({ signal }) => getPhotoVisibility(photoId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(photoId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPhotoVisibility>>, TError, TData> & { queryKey: QueryKey }
}

export type GetPhotoVisibilityQueryResult = NonNullable<Awaited<ReturnType<typeof getPhotoVisibility>>>
export type GetPhotoVisibilityQueryError = ErrorType<unknown>


/**
 * @summary Get visibility rule for a photo
 */

export function useGetPhotoVisibility<TData = Awaited<ReturnType<typeof getPhotoVisibility>>, TError = ErrorType<unknown>>(
 photoId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getPhotoVisibility>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetPhotoVisibilityQueryOptions(photoId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getSetPhotoVisibilityUrl = (photoId: number,) => {




  return `/api/photos/${photoId}/visibility`
}

/**
 * @summary Set visibility rule for a photo
 */
export const setPhotoVisibility = async (photoId: number,
    visibilityInput: VisibilityInput, options?: RequestInit): Promise<VisibilityRule> => {

  return customFetch<VisibilityRule>(getSetPhotoVisibilityUrl(photoId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      visibilityInput,)
  }
);}




export const getSetPhotoVisibilityMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setPhotoVisibility>>, TError,{photoId: number;data: BodyType<VisibilityInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof setPhotoVisibility>>, TError,{photoId: number;data: BodyType<VisibilityInput>}, TContext> => {

const mutationKey = ['setPhotoVisibility'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof setPhotoVisibility>>, {photoId: number;data: BodyType<VisibilityInput>}> = (props) => {
          const {photoId,data} = props ?? {};

          return  setPhotoVisibility(photoId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SetPhotoVisibilityMutationResult = NonNullable<Awaited<ReturnType<typeof setPhotoVisibility>>>
    export type SetPhotoVisibilityMutationBody = BodyType<VisibilityInput>
    export type SetPhotoVisibilityMutationError = ErrorType<unknown>

    /**
 * @summary Set visibility rule for a photo
 */
export const useSetPhotoVisibility = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof setPhotoVisibility>>, TError,{photoId: number;data: BodyType<VisibilityInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof setPhotoVisibility>>,
        TError,
        {photoId: number;data: BodyType<VisibilityInput>},
        TContext
      > => {
      return useMutation(getSetPhotoVisibilityMutationOptions(options));
    }

export const getPreviewAsContactUrl = (contactId: number,) => {




  return `/api/preview/${contactId}`
}

/**
 * @summary Preview which photo a specific contact would see
 */
export const previewAsContact = async (contactId: number, options?: RequestInit): Promise<VisibilityPreview> => {

  return customFetch<VisibilityPreview>(getPreviewAsContactUrl(contactId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getPreviewAsContactQueryKey = (contactId: number,) => {
    return [
    `/api/preview/${contactId}`
    ] as const;
    }


export const getPreviewAsContactQueryOptions = <TData = Awaited<ReturnType<typeof previewAsContact>>, TError = ErrorType<unknown>>(contactId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof previewAsContact>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPreviewAsContactQueryKey(contactId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof previewAsContact>>> = ({ signal }) => previewAsContact(contactId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(contactId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof previewAsContact>>, TError, TData> & { queryKey: QueryKey }
}

export type PreviewAsContactQueryResult = NonNullable<Awaited<ReturnType<typeof previewAsContact>>>
export type PreviewAsContactQueryError = ErrorType<unknown>


/**
 * @summary Preview which photo a specific contact would see
 */

export function usePreviewAsContact<TData = Awaited<ReturnType<typeof previewAsContact>>, TError = ErrorType<unknown>>(
 contactId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof previewAsContact>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getPreviewAsContactQueryOptions(contactId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListContactsUrl = () => {




  return `/api/contacts`
}

/**
 * @summary List all contacts
 */
export const listContacts = async ( options?: RequestInit): Promise<Contact[]> => {

  return customFetch<Contact[]>(getListContactsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListContactsQueryKey = () => {
    return [
    `/api/contacts`
    ] as const;
    }


export const getListContactsQueryOptions = <TData = Awaited<ReturnType<typeof listContacts>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListContactsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listContacts>>> = ({ signal }) => listContacts({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListContactsQueryResult = NonNullable<Awaited<ReturnType<typeof listContacts>>>
export type ListContactsQueryError = ErrorType<unknown>


/**
 * @summary List all contacts
 */

export function useListContacts<TData = Awaited<ReturnType<typeof listContacts>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listContacts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListContactsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateContactUrl = () => {




  return `/api/contacts`
}

/**
 * @summary Add a new contact
 */
export const createContact = async (contactInput: ContactInput, options?: RequestInit): Promise<Contact> => {

  return customFetch<Contact>(getCreateContactUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactInput,)
  }
);}




export const getCreateContactMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: BodyType<ContactInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: BodyType<ContactInput>}, TContext> => {

const mutationKey = ['createContact'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContact>>, {data: BodyType<ContactInput>}> = (props) => {
          const {data} = props ?? {};

          return  createContact(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateContactMutationResult = NonNullable<Awaited<ReturnType<typeof createContact>>>
    export type CreateContactMutationBody = BodyType<ContactInput>
    export type CreateContactMutationError = ErrorType<unknown>

    /**
 * @summary Add a new contact
 */
export const useCreateContact = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContact>>, TError,{data: BodyType<ContactInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createContact>>,
        TError,
        {data: BodyType<ContactInput>},
        TContext
      > => {
      return useMutation(getCreateContactMutationOptions(options));
    }

export const getUpdateContactUrl = (contactId: number,) => {




  return `/api/contacts/${contactId}`
}

/**
 * @summary Update a contact
 */
export const updateContact = async (contactId: number,
    contactUpdate: ContactUpdate, options?: RequestInit): Promise<Contact> => {

  return customFetch<Contact>(getUpdateContactUrl(contactId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactUpdate,)
  }
);}




export const getUpdateContactMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{contactId: number;data: BodyType<ContactUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{contactId: number;data: BodyType<ContactUpdate>}, TContext> => {

const mutationKey = ['updateContact'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContact>>, {contactId: number;data: BodyType<ContactUpdate>}> = (props) => {
          const {contactId,data} = props ?? {};

          return  updateContact(contactId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateContactMutationResult = NonNullable<Awaited<ReturnType<typeof updateContact>>>
    export type UpdateContactMutationBody = BodyType<ContactUpdate>
    export type UpdateContactMutationError = ErrorType<unknown>

    /**
 * @summary Update a contact
 */
export const useUpdateContact = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContact>>, TError,{contactId: number;data: BodyType<ContactUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateContact>>,
        TError,
        {contactId: number;data: BodyType<ContactUpdate>},
        TContext
      > => {
      return useMutation(getUpdateContactMutationOptions(options));
    }

export const getDeleteContactUrl = (contactId: number,) => {




  return `/api/contacts/${contactId}`
}

/**
 * @summary Remove a contact
 */
export const deleteContact = async (contactId: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteContactUrl(contactId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteContactMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{contactId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{contactId: number}, TContext> => {

const mutationKey = ['deleteContact'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContact>>, {contactId: number}> = (props) => {
          const {contactId} = props ?? {};

          return  deleteContact(contactId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContact>>>

    export type DeleteContactMutationError = ErrorType<unknown>

    /**
 * @summary Remove a contact
 */
export const useDeleteContact = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContact>>, TError,{contactId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteContact>>,
        TError,
        {contactId: number},
        TContext
      > => {
      return useMutation(getDeleteContactMutationOptions(options));
    }

export const getListContactListsUrl = () => {




  return `/api/lists`
}

/**
 * @summary List all custom contact lists
 */
export const listContactLists = async ( options?: RequestInit): Promise<ContactList[]> => {

  return customFetch<ContactList[]>(getListContactListsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListContactListsQueryKey = () => {
    return [
    `/api/lists`
    ] as const;
    }


export const getListContactListsQueryOptions = <TData = Awaited<ReturnType<typeof listContactLists>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listContactLists>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListContactListsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listContactLists>>> = ({ signal }) => listContactLists({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listContactLists>>, TError, TData> & { queryKey: QueryKey }
}

export type ListContactListsQueryResult = NonNullable<Awaited<ReturnType<typeof listContactLists>>>
export type ListContactListsQueryError = ErrorType<unknown>


/**
 * @summary List all custom contact lists
 */

export function useListContactLists<TData = Awaited<ReturnType<typeof listContactLists>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listContactLists>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListContactListsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateContactListUrl = () => {




  return `/api/lists`
}

/**
 * @summary Create a custom contact list
 */
export const createContactList = async (contactListInput: ContactListInput, options?: RequestInit): Promise<ContactList> => {

  return customFetch<ContactList>(getCreateContactListUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactListInput,)
  }
);}




export const getCreateContactListMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContactList>>, TError,{data: BodyType<ContactListInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createContactList>>, TError,{data: BodyType<ContactListInput>}, TContext> => {

const mutationKey = ['createContactList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createContactList>>, {data: BodyType<ContactListInput>}> = (props) => {
          const {data} = props ?? {};

          return  createContactList(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateContactListMutationResult = NonNullable<Awaited<ReturnType<typeof createContactList>>>
    export type CreateContactListMutationBody = BodyType<ContactListInput>
    export type CreateContactListMutationError = ErrorType<unknown>

    /**
 * @summary Create a custom contact list
 */
export const useCreateContactList = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createContactList>>, TError,{data: BodyType<ContactListInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createContactList>>,
        TError,
        {data: BodyType<ContactListInput>},
        TContext
      > => {
      return useMutation(getCreateContactListMutationOptions(options));
    }

export const getUpdateContactListUrl = (listId: number,) => {




  return `/api/lists/${listId}`
}

/**
 * @summary Rename a contact list
 */
export const updateContactList = async (listId: number,
    contactListUpdate: ContactListUpdate, options?: RequestInit): Promise<ContactList> => {

  return customFetch<ContactList>(getUpdateContactListUrl(listId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      contactListUpdate,)
  }
);}




export const getUpdateContactListMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContactList>>, TError,{listId: number;data: BodyType<ContactListUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateContactList>>, TError,{listId: number;data: BodyType<ContactListUpdate>}, TContext> => {

const mutationKey = ['updateContactList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateContactList>>, {listId: number;data: BodyType<ContactListUpdate>}> = (props) => {
          const {listId,data} = props ?? {};

          return  updateContactList(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateContactListMutationResult = NonNullable<Awaited<ReturnType<typeof updateContactList>>>
    export type UpdateContactListMutationBody = BodyType<ContactListUpdate>
    export type UpdateContactListMutationError = ErrorType<unknown>

    /**
 * @summary Rename a contact list
 */
export const useUpdateContactList = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateContactList>>, TError,{listId: number;data: BodyType<ContactListUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateContactList>>,
        TError,
        {listId: number;data: BodyType<ContactListUpdate>},
        TContext
      > => {
      return useMutation(getUpdateContactListMutationOptions(options));
    }

export const getDeleteContactListUrl = (listId: number,) => {




  return `/api/lists/${listId}`
}

/**
 * @summary Delete a custom list
 */
export const deleteContactList = async (listId: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteContactListUrl(listId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteContactListMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactList>>, TError,{listId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteContactList>>, TError,{listId: number}, TContext> => {

const mutationKey = ['deleteContactList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteContactList>>, {listId: number}> = (props) => {
          const {listId} = props ?? {};

          return  deleteContactList(listId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteContactListMutationResult = NonNullable<Awaited<ReturnType<typeof deleteContactList>>>

    export type DeleteContactListMutationError = ErrorType<unknown>

    /**
 * @summary Delete a custom list
 */
export const useDeleteContactList = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteContactList>>, TError,{listId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteContactList>>,
        TError,
        {listId: number},
        TContext
      > => {
      return useMutation(getDeleteContactListMutationOptions(options));
    }

export const getListContactListMembersUrl = (listId: number,) => {




  return `/api/lists/${listId}/members`
}

/**
 * @summary Get members of a list
 */
export const listContactListMembers = async (listId: number, options?: RequestInit): Promise<Contact[]> => {

  return customFetch<Contact[]>(getListContactListMembersUrl(listId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListContactListMembersQueryKey = (listId: number,) => {
    return [
    `/api/lists/${listId}/members`
    ] as const;
    }


export const getListContactListMembersQueryOptions = <TData = Awaited<ReturnType<typeof listContactListMembers>>, TError = ErrorType<unknown>>(listId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listContactListMembers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListContactListMembersQueryKey(listId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listContactListMembers>>> = ({ signal }) => listContactListMembers(listId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(listId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listContactListMembers>>, TError, TData> & { queryKey: QueryKey }
}

export type ListContactListMembersQueryResult = NonNullable<Awaited<ReturnType<typeof listContactListMembers>>>
export type ListContactListMembersQueryError = ErrorType<unknown>


/**
 * @summary Get members of a list
 */

export function useListContactListMembers<TData = Awaited<ReturnType<typeof listContactListMembers>>, TError = ErrorType<unknown>>(
 listId: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listContactListMembers>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListContactListMembersQueryOptions(listId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getAddContactToListUrl = (listId: number,) => {




  return `/api/lists/${listId}/members`
}

/**
 * @summary Add a contact to a list
 */
export const addContactToList = async (listId: number,
    listMemberInput: ListMemberInput, options?: RequestInit): Promise<Contact> => {

  return customFetch<Contact>(getAddContactToListUrl(listId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      listMemberInput,)
  }
);}




export const getAddContactToListMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addContactToList>>, TError,{listId: number;data: BodyType<ListMemberInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof addContactToList>>, TError,{listId: number;data: BodyType<ListMemberInput>}, TContext> => {

const mutationKey = ['addContactToList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addContactToList>>, {listId: number;data: BodyType<ListMemberInput>}> = (props) => {
          const {listId,data} = props ?? {};

          return  addContactToList(listId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddContactToListMutationResult = NonNullable<Awaited<ReturnType<typeof addContactToList>>>
    export type AddContactToListMutationBody = BodyType<ListMemberInput>
    export type AddContactToListMutationError = ErrorType<unknown>

    /**
 * @summary Add a contact to a list
 */
export const useAddContactToList = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addContactToList>>, TError,{listId: number;data: BodyType<ListMemberInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof addContactToList>>,
        TError,
        {listId: number;data: BodyType<ListMemberInput>},
        TContext
      > => {
      return useMutation(getAddContactToListMutationOptions(options));
    }

export const getRemoveContactFromListUrl = (listId: number,
    contactId: number,) => {




  return `/api/lists/${listId}/members/${contactId}`
}

/**
 * @summary Remove a contact from a list
 */
export const removeContactFromList = async (listId: number,
    contactId: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getRemoveContactFromListUrl(listId,contactId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getRemoveContactFromListMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeContactFromList>>, TError,{listId: number;contactId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof removeContactFromList>>, TError,{listId: number;contactId: number}, TContext> => {

const mutationKey = ['removeContactFromList'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeContactFromList>>, {listId: number;contactId: number}> = (props) => {
          const {listId,contactId} = props ?? {};

          return  removeContactFromList(listId,contactId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveContactFromListMutationResult = NonNullable<Awaited<ReturnType<typeof removeContactFromList>>>

    export type RemoveContactFromListMutationError = ErrorType<unknown>

    /**
 * @summary Remove a contact from a list
 */
export const useRemoveContactFromList = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeContactFromList>>, TError,{listId: number;contactId: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof removeContactFromList>>,
        TError,
        {listId: number;contactId: number},
        TContext
      > => {
      return useMutation(getRemoveContactFromListMutationOptions(options));
    }

