/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns a presigned GCS URL for direct upload. Send JSON metadata only — NOT the file.
Then upload the file directly to the returned presigned URL via PUT.

 * @summary Request a presigned URL for file upload
 */





export const RequestUploadUrlBody = zod.object({
  "name": zod.string().min(1).describe('Original file name'),
  "size": zod.number().min(1).describe('File size in bytes'),
  "contentType": zod.string().min(1).describe('MIME type (e.g. image\/jpeg)')
})

export const RequestUploadUrlResponse = zod.object({
  "uploadURL": zod.string().describe('Presigned GCS URL for PUT upload'),
  "objectPath": zod.string().describe('Normalized object path (e.g. \/objects\/uploads\/uuid)')
})


/**
 * @summary Serve an uploaded object
 */
export const GetStorageObjectParams = zod.object({
  "objectPath": zod.coerce.string()
})


/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get current user profile
 */
export const GetMeResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "username": zod.string(),
  "bio": zod.string().nullish(),
  "defaultPhotoId": zod.number().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Update current user profile
 */



export const UpdateMeBody = zod.object({
  "name": zod.string().min(1).optional(),
  "bio": zod.string().optional()
})

export const UpdateMeResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "username": zod.string(),
  "bio": zod.string().nullish(),
  "defaultPhotoId": zod.number().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Get dashboard summary stats
 */
export const GetMyStatsResponse = zod.object({
  "totalPhotos": zod.number(),
  "activeRules": zod.number(),
  "totalContacts": zod.number(),
  "totalLists": zod.number(),
  "publicPhotoId": zod.number().nullable()
})


/**
 * @summary List all profile photos for current user
 */
export const ListPhotosResponseItem = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "label": zod.string(),
  "imageUrl": zod.string(),
  "isDefault": zod.boolean(),
  "visibilityType": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})
export const ListPhotosResponse = zod.array(ListPhotosResponseItem)


/**
 * @summary Upload a new profile photo
 */



export const CreatePhotoBody = zod.object({
  "label": zod.string().min(1),
  "imageUrl": zod.string(),
  "isDefault": zod.boolean().optional()
})


/**
 * @summary Get a specific profile photo
 */
export const GetPhotoParams = zod.object({
  "photoId": zod.coerce.number()
})

export const GetPhotoResponse = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "label": zod.string(),
  "imageUrl": zod.string(),
  "isDefault": zod.boolean(),
  "visibilityType": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Update photo label or set as default
 */
export const UpdatePhotoParams = zod.object({
  "photoId": zod.coerce.number()
})




export const UpdatePhotoBody = zod.object({
  "label": zod.string().min(1).optional(),
  "isDefault": zod.boolean().optional()
})

export const UpdatePhotoResponse = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "label": zod.string(),
  "imageUrl": zod.string(),
  "isDefault": zod.boolean(),
  "visibilityType": zod.string().nullish(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete a profile photo
 */
export const DeletePhotoParams = zod.object({
  "photoId": zod.coerce.number()
})


/**
 * @summary Get visibility rule for a photo
 */
export const GetPhotoVisibilityParams = zod.object({
  "photoId": zod.coerce.number()
})

export const GetPhotoVisibilityResponse = zod.object({
  "photoId": zod.number(),
  "type": zod.enum(['public', 'contacts', 'selected', 'custom_list', 'nobody']),
  "selectedContactIds": zod.array(zod.number()).optional(),
  "listId": zod.number().nullish(),
  "excludedContactIds": zod.array(zod.number()).optional()
})


/**
 * @summary Set visibility rule for a photo
 */
export const SetPhotoVisibilityParams = zod.object({
  "photoId": zod.coerce.number()
})

export const SetPhotoVisibilityBody = zod.object({
  "type": zod.enum(['public', 'contacts', 'selected', 'custom_list', 'nobody']),
  "selectedContactIds": zod.array(zod.number()).optional(),
  "listId": zod.number().nullish(),
  "excludedContactIds": zod.array(zod.number()).optional()
})

export const SetPhotoVisibilityResponse = zod.object({
  "photoId": zod.number(),
  "type": zod.enum(['public', 'contacts', 'selected', 'custom_list', 'nobody']),
  "selectedContactIds": zod.array(zod.number()).optional(),
  "listId": zod.number().nullish(),
  "excludedContactIds": zod.array(zod.number()).optional()
})


/**
 * @summary Preview which photo a specific contact would see
 */
export const PreviewAsContactParams = zod.object({
  "contactId": zod.coerce.number()
})

export const PreviewAsContactResponse = zod.object({
  "contactId": zod.number(),
  "photoId": zod.number(),
  "reason": zod.string(),
  "photo": zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "label": zod.string(),
  "imageUrl": zod.string(),
  "isDefault": zod.boolean(),
  "visibilityType": zod.string().nullish(),
  "createdAt": zod.coerce.date()
}).optional()
})


/**
 * @summary List all contacts
 */
export const ListContactsResponseItem = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "name": zod.string(),
  "handle": zod.string().nullish(),
  "avatarUrl": zod.string().nullish(),
  "listIds": zod.array(zod.number()).optional(),
  "createdAt": zod.coerce.date()
})
export const ListContactsResponse = zod.array(ListContactsResponseItem)


/**
 * @summary Add a new contact
 */



export const CreateContactBody = zod.object({
  "name": zod.string().min(1),
  "handle": zod.string().optional(),
  "avatarUrl": zod.string().optional()
})


/**
 * @summary Update a contact
 */
export const UpdateContactParams = zod.object({
  "contactId": zod.coerce.number()
})




export const UpdateContactBody = zod.object({
  "name": zod.string().min(1).optional(),
  "handle": zod.string().optional(),
  "avatarUrl": zod.string().optional()
})

export const UpdateContactResponse = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "name": zod.string(),
  "handle": zod.string().nullish(),
  "avatarUrl": zod.string().nullish(),
  "listIds": zod.array(zod.number()).optional(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Remove a contact
 */
export const DeleteContactParams = zod.object({
  "contactId": zod.coerce.number()
})


/**
 * @summary List all custom contact lists
 */
export const ListContactListsResponseItem = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "name": zod.string(),
  "memberCount": zod.number(),
  "createdAt": zod.coerce.date()
})
export const ListContactListsResponse = zod.array(ListContactListsResponseItem)


/**
 * @summary Create a custom contact list
 */



export const CreateContactListBody = zod.object({
  "name": zod.string().min(1)
})


/**
 * @summary Rename a contact list
 */
export const UpdateContactListParams = zod.object({
  "listId": zod.coerce.number()
})




export const UpdateContactListBody = zod.object({
  "name": zod.string().min(1).optional()
})

export const UpdateContactListResponse = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "name": zod.string(),
  "memberCount": zod.number(),
  "createdAt": zod.coerce.date()
})


/**
 * @summary Delete a custom list
 */
export const DeleteContactListParams = zod.object({
  "listId": zod.coerce.number()
})


/**
 * @summary Get members of a list
 */
export const ListContactListMembersParams = zod.object({
  "listId": zod.coerce.number()
})

export const ListContactListMembersResponseItem = zod.object({
  "id": zod.number(),
  "userId": zod.number(),
  "name": zod.string(),
  "handle": zod.string().nullish(),
  "avatarUrl": zod.string().nullish(),
  "listIds": zod.array(zod.number()).optional(),
  "createdAt": zod.coerce.date()
})
export const ListContactListMembersResponse = zod.array(ListContactListMembersResponseItem)


/**
 * @summary Add a contact to a list
 */
export const AddContactToListParams = zod.object({
  "listId": zod.coerce.number()
})

export const AddContactToListBody = zod.object({
  "contactId": zod.number()
})


/**
 * @summary Remove a contact from a list
 */
export const RemoveContactFromListParams = zod.object({
  "listId": zod.coerce.number(),
  "contactId": zod.coerce.number()
})


