/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
export interface Contact {
    id: number;
    userId: number;
    name: string;
    /** @nullable */
    handle?: string | null;
    /** @nullable */
    avatarUrl?: string | null;
    listIds?: number[];
    createdAt: Date;
}
//# sourceMappingURL=contact.d.ts.map