/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
export interface StorageUploadRequest {
    /**
       * Original file name
       * @minLength 1
       */
    name: string;
    /**
       * File size in bytes
       * @minimum 1
       */
    size: number;
    /**
       * MIME type (e.g. image/jpeg)
       * @minLength 1
       */
    contentType: string;
}
//# sourceMappingURL=storageUploadRequest.d.ts.map