/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
export interface StorageUploadResponse {
    /** Presigned GCS URL for PUT upload */
    uploadURL: string;
    /** Normalized object path (e.g. /objects/uploads/uuid) */
    objectPath: string;
}
//# sourceMappingURL=storageUploadResponse.d.ts.map