/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
export interface UserUpdate {
    /** @minLength 1 */
    name?: string;
    bio?: string;
}
//# sourceMappingURL=userUpdate.d.ts.map