/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */

export interface User {
  id: number;
  name: string;
  username: string;
  /** @nullable */
  bio?: string | null;
  /** @nullable */
  defaultPhotoId?: number | null;
  createdAt: Date;
}
