/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
export interface UserStats {
    totalPhotos: number;
    activeRules: number;
    totalContacts: number;
    totalLists: number;
    /** @nullable */
    publicPhotoId: number | null;
}
//# sourceMappingURL=userStats.d.ts.map