/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
import type { VisibilityType } from './visibilityType';
export interface VisibilityInput {
    type: VisibilityType;
    selectedContactIds?: number[];
    /** @nullable */
    listId?: number | null;
    excludedContactIds?: number[];
}
//# sourceMappingURL=visibilityInput.d.ts.map