/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
export type VisibilityType = typeof VisibilityType[keyof typeof VisibilityType];
export declare const VisibilityType: {
    readonly public: "public";
    readonly contacts: "contacts";
    readonly selected: "selected";
    readonly custom_list: "custom_list";
    readonly nobody: "nobody";
};
//# sourceMappingURL=visibilityType.d.ts.map