/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */

export type VisibilityType = typeof VisibilityType[keyof typeof VisibilityType];


export const VisibilityType = {
  public: 'public',
  contacts: 'contacts',
  selected: 'selected',
  custom_list: 'custom_list',
  nobody: 'nobody',
} as const;
