/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ProfileLens API — privacy-first multi-photo profile visibility
 * OpenAPI spec version: 0.1.0
 */
import type { ProfilePhoto } from './profilePhoto';

export interface VisibilityPreview {
  contactId: number;
  photoId: number;
  reason: string;
  photo?: ProfilePhoto;
}
